apiVersion: v1
kind: Service
metadata:
  name: application-web
spec:
  selector:
    app: application-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: postgre
# spec:
#   selector:
#     app: postgre
#   ports:
#     - port: 5432