services:
  postgre:
    image: postgres:13.13
    ports:
      - 5432:5432
    environment:
      DB_DATABASE: ${DB_DATABASE} # Variaveis passadas local .env
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

  kubenews:
    image: davicarneiro/kube-news:v1
    depends_on:
      - postgre
    build:
      context: ./src
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    environment:
      DB_DATABASE: ${DB_DATABASE} # Variaveis passadas local .env
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}

networks:
  kubenews_networks:
    driver: bridge


